export const MockPageContent = {
  data: {
    pageContents: [
      {
        title: "Nimbus Tech - Expert Software & Cloud Consulting",
        slug: "home",
        image: {
          id: "cmirrv6jr000414iw7k0pvia1",
          width: 1600,
          height: 900,
          src: "/images/hero-bg.png",
          alt: "Nimbus Tech hero background",
          fill: false,
          className: "",
        },
        id: "cmirrv6oq003j14iwb6m3aki0",
        description:
          "Custom software development, cloud architecture, and scalable solutions for modern enterprises.",
        cta: {
          id: "cmirrv6op003i14iwfg900ltf",
          label: "Get Started",
          href: "#features",
          external: false,
        },
        sections: [
          {
            id: "cmirrv6m2002y14iwi88czxs9",
            type: "benefits",
            contentHero: null,
            contentBenefits: {
              id: "cmirrv6lf000t14iwz5t8su53",
              title: "Your Benefits with Nimbus Tech",
              benefits: [
                {
                  id: "cmirrv6le000q14iwxxpfo236",
                  icon: "RiAwardFill",
                  title: "Certified Experts",
                  description:
                    "We are experienced and certified AWS cloud specialists.",
                },
                {
                  id: "cmirrv6le000r14iwssk2mm9d",
                  icon: "RiMoneyEuroBoxFill",
                  title: "Full Cost Control",
                  description:
                    "We ensure transparent and predictable costs for your cloud project.",
                },
                {
                  id: "cmirrv6le000s14iwjn3m8vin",
                  icon: "RiFlashlightFill",
                  title: "Fast Implementation",
                  description:
                    "We implement your individual cloud project efficiently and quickly.",
                },
              ],
              benefitsCount: 3,
            },
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: null,
            contentCertifications: null,
            contentApproach: null,
            contentAbout: null,
            contentAnalytics: null,
            contentNavigation: null,
            contentFooter: null,
            contentCta: null,
            contentMap: null,
          },
          {
            id: "cmirrv6m2002z14iw3yu35mwx",
            type: "features",
            contentHero: null,
            contentBenefits: null,
            contentFeatures: [
              {
                id: "cmirrv6lg000u14iwfk1b2zrl",
                featureId: 1,
                title: "Cloud Architecture",
                description:
                  "Design and implement scalable, secure cloud solutions.",
                longDescription:
                  "Our expert team designs robust cloud architectures tailored to your business needs, ensuring scalability, security, and cost-effectiveness.",
                visualization: "ArchitectureFeatureVisualization",
              },
              {
                id: "cmirrv6lg000v14iw0u2zpxdm",
                featureId: 2,
                title: "DevOps & Automation",
                description:
                  "Streamline your development and operations workflows.",
                longDescription:
                  "We implement CI/CD pipelines, infrastructure as code, and automated testing to accelerate your delivery and improve reliability.",
                visualization: "CloudFeatureVisualization",
              },
              {
                id: "cmirrv6lg000w14iwezx3wvyk",
                featureId: 3,
                title: "Custom Software Development",
                description:
                  "Build tailored solutions for your unique requirements.",
                longDescription:
                  "From concept to deployment, we develop custom software applications using modern technologies and best practices.",
                visualization: "OrbitFeatureVisualization",
              },
            ],
            contentFeaturesCount: 3,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: null,
            contentCertifications: null,
            contentApproach: null,
            contentAbout: null,
            contentAnalytics: null,
            contentNavigation: null,
            contentFooter: null,
            contentCta: null,
            contentMap: null,
          },
          {
            id: "cmirrv6m2003014iwcjqbt6d5",
            type: "certifications",
            contentHero: null,
            contentBenefits: null,
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: null,
            contentCertifications: {
              id: "cmirrv6lj001h14iwfrr97cb4",
              title: "Our Certifications",
              description:
                "Industry-recognized certifications demonstrating our expertise in software architecture and cloud technologies.",
              cta: {
                id: "cmirrv6li001g14iwkgjffhjd",
                label: "View All Certifications",
                href: "#certifications",
                external: false,
              },
              certifications: [
                {
                  id: "cmirrv6li001a14iw6an4e60z",
                  certId: 1,
                  title:
                    "iSAQB® Certified Professional for Software Architecture - Advanced Level (CPSA-A)",
                  description:
                    "Advanced certification in software architecture methodology and practice.",
                  image: {
                    id: "cmirrv6js000914iwamjxkbgl",
                    src: "/images/certifications/isaqb-advanced.png",
                    alt: "CPSA-A certification badge",
                    width: 200,
                    height: 200,
                    fill: false,
                    className: "",
                  },
                  link: "",
                },
                {
                  id: "cmirrv6li001b14iwjd91ncfk",
                  certId: 2,
                  title: "AWS Certified Solutions Architect - Professional",
                  description:
                    "Expert-level certification for designing distributed systems on AWS.",
                  image: {
                    id: "cmirrv6js000714iwsir1of15",
                    src: "/images/certifications/aws-solutions-architect-pro.png",
                    alt: "AWS Solutions Architect Professional badge",
                    width: 200,
                    height: 200,
                    fill: false,
                    className: "",
                  },
                  link: "https://aws.amazon.com/certification/certified-solutions-architect-professional/",
                },
                {
                  id: "cmirrv6li001c14iwa1effaba",
                  certId: 3,
                  title: "AWS Certified Developer - Associate",
                  description:
                    "Validates technical expertise in developing and maintaining AWS applications.",
                  image: {
                    id: "cmirrv6js000814iw5cms3xxr",
                    src: "/images/certifications/aws-developer-associate.png",
                    alt: "AWS Certified Developer badge",
                    width: 200,
                    height: 200,
                    fill: false,
                    className: "",
                  },
                  link: "https://aws.amazon.com/certification/certified-developer-associate/",
                },
                {
                  id: "cmirrv6li001d14iwx9csf9eh",
                  certId: 4,
                  title: "Certified Kubernetes Administrator (CKA)",
                  description:
                    "Demonstrates skills in Kubernetes administration and deployment.",
                  image: {
                    id: "cmirrv6js000a14iwkyhpwhap",
                    src: "/images/certifications/cka.png",
                    alt: "Certified Kubernetes Administrator badge",
                    width: 200,
                    height: 200,
                    fill: false,
                    className: "",
                  },
                  link: "https://www.cncf.io/certification/cka/",
                },
                {
                  id: "cmirrv6li001e14iwq3dkufou",
                  certId: 5,
                  title: "HashiCorp Certified: Terraform Associate",
                  description:
                    "Validates knowledge of Terraform and infrastructure as code practices.",
                  image: {
                    id: "cmirrv6jt000b14iw5v3qhba1",
                    src: "/images/certifications/terraform-associate.png",
                    alt: "Terraform Associate badge",
                    width: 200,
                    height: 200,
                    fill: false,
                    className: "",
                  },
                  link: "https://www.hashicorp.com/certification/terraform-associate",
                },
                {
                  id: "cmirrv6li001f14iwjd7rkqbw",
                  certId: 6,
                  title: "Certified ScrumMaster (CSM)",
                  description:
                    "Demonstrates understanding of Scrum framework and agile methodologies.",
                  image: {
                    id: "cmirrv6k8000c14iwad2edw61",
                    src: "/images/certifications/csm.png",
                    alt: "Certified ScrumMaster badge",
                    width: 200,
                    height: 200,
                    fill: false,
                    className: "",
                  },
                  link: "",
                },
              ],
              certificationsCount: 6,
            },
            contentApproach: null,
            contentAbout: null,
            contentAnalytics: null,
            contentNavigation: null,
            contentFooter: null,
            contentCta: null,
            contentMap: null,
          },
          {
            id: "cmirrv6m2003114iw6ppy752d",
            type: "hero",
            contentHero: {
              id: "cmirrv6le000p14iw3f9h7pqx",
              subHeading:
                "Expert Software & Cloud Consulting, Wherever You Are",
              banner: {
                id: "cmirrv6le000n14iw6olmy295",
                label: "🚀 Launch Your Cloud Journey",
                href: "#features",
                external: false,
                icon: "",
                additional: {
                  id: "cmirrv6ld000l14iwmbanw3pg",
                  icon: "RiArrowRightSLine",
                  text: "Get Started",
                },
              },
            },
            contentBenefits: null,
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: null,
            contentCertifications: null,
            contentApproach: null,
            contentAbout: null,
            contentAnalytics: null,
            contentNavigation: null,
            contentFooter: null,
            contentCta: null,
            contentMap: null,
          },
          {
            id: "cmirrv6m2003314iw45zsbsj2",
            type: "testimonials",
            contentHero: null,
            contentBenefits: null,
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: {
              id: "cmirrv6lh001914iwp3ezeesg",
              title: "",
              background: [
                {
                  id: "cmirrv6l3000i14iwmihtdsna",
                  image: {
                    id: "cmirrv6jr000214iwaaxj374y",
                    src: "/images/drone.png",
                    alt: "drone in the sky",
                    width: 1583,
                    height: 554,
                    fill: false,
                    className: "animate-hover",
                  },
                  outerClassName:
                    "absolute top-[19rem] -right-14 w-[19rem] sm:top-[12rem] sm:right-3 sm:w-[23rem] md:top-[12rem] md:right-0 md:w-[25rem] lg:top-[16rem] lg:right-12 lg:w-[34rem]",
                },
                {
                  id: "cmirrv6l3000j14iw336lt57c",
                  image: {
                    id: "cmirrv6jr000614iw5zgvrblr",
                    src: "/images/field.png",
                    alt: "clouds background",
                    width: null,
                    height: null,
                    fill: true,
                    className: "object-cover",
                  },
                  outerClassName: "absolute inset-0 object-cover",
                },
              ],
              backgroundCount: 2,
              testimonials: [],
              testimonialsCount: 0,
              fallback: {
                id: "cmirrv6lh001714iw9mb4pv84",
                rating: null,
                name: "The Nimbus Tech Team",
                role: "Software & Cloud Experts",
                company: "Nimbus Tech",
                content:
                  "As Nimbus Tech launches, we look forward to partnering with innovative organizations and delivering exceptional software and cloud solutions. Your feedback could be featured here!",
              },
            },
            contentCertifications: null,
            contentApproach: null,
            contentAbout: null,
            contentAnalytics: null,
            contentNavigation: null,
            contentFooter: null,
            contentCta: null,
            contentMap: null,
          },
          {
            id: "cmirrv6m2003414iwkuxie6f8",
            type: "approach",
            contentHero: null,
            contentBenefits: null,
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: null,
            contentCertifications: null,
            contentApproach: {
              id: "cmirrv6lk001n14iwyp7uhhle",
              title: "Our Approach",
              description:
                "We follow a proven methodology to deliver successful projects on time and within budget.",
              steps: [
                {
                  id: "cmirrv6lj001i14iww4027b7y",
                  stepId: 1,
                  type: "done",
                  title: "Discovery & Planning",
                  description:
                    "We analyze your requirements, define objectives, and create a detailed project roadmap.",
                  activityTime: "Week 1-2",
                },
                {
                  id: "cmirrv6lj001j14iw5cvlgydx",
                  stepId: 2,
                  type: "in progress",
                  title: "Design & Architecture",
                  description:
                    "Our team designs the system architecture and creates technical specifications.",
                  activityTime: "Week 2-4",
                },
                {
                  id: "cmirrv6lj001k14iwayqapbc3",
                  stepId: 3,
                  type: "open",
                  title: "Development & Testing",
                  description:
                    "We build your solution using agile sprints with continuous testing and feedback.",
                  activityTime: "Week 4-10",
                },
                {
                  id: "cmirrv6lj001l14iw4szs5yfq",
                  stepId: 4,
                  type: "open",
                  title: "Deployment & Launch",
                  description:
                    "We deploy to production with comprehensive monitoring and support.",
                  activityTime: "Week 10-12",
                },
                {
                  id: "cmirrv6lj001m14iwp9e63ehb",
                  stepId: 5,
                  type: "open",
                  title: "Optimization & Support",
                  description:
                    "Ongoing maintenance, performance optimization, and feature enhancements.",
                  activityTime: "Ongoing",
                },
              ],
              stepsCount: 5,
            },
            contentAbout: null,
            contentAnalytics: null,
            contentNavigation: null,
            contentFooter: null,
            contentCta: null,
            contentMap: null,
          },
          {
            id: "cmirrv6m2003a14iwqjg87emm",
            type: "faq",
            contentHero: null,
            contentBenefits: null,
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [
              {
                id: "cmirrv6lg000x14iw3o1hmeyc",
                question: "What cloud platforms do you support?",
                answer:
                  "We specialize in AWS but also work with Azure, Google Cloud, and multi-cloud architectures.",
              },
              {
                id: "cmirrv6lg000y14iwnnxao7dy",
                question: "How long does a typical project take?",
                answer:
                  "Project timelines vary based on complexity, but we typically deliver MVPs within 8-12 weeks.",
              },
              {
                id: "cmirrv6lg000z14iwxs6dcfjw",
                question: "Do you provide ongoing support?",
                answer:
                  "Yes, we offer maintenance, monitoring, and support packages tailored to your needs.",
              },
              {
                id: "cmirrv6lg001014iwyxil49rj",
                question: "What industries do you serve?",
                answer:
                  "We work with clients across various industries including fintech, healthcare, e-commerce, and SaaS.",
              },
              {
                id: "cmirrv6lg001114iwxy1auvt2",
                question:
                  "Can you help migrate existing applications to the cloud?",
                answer:
                  "Absolutely! We have extensive experience in cloud migration strategies and implementations.",
              },
              {
                id: "cmirrv6lg001214iwsx804od1",
                question: "What is your development approach?",
                answer:
                  "We follow agile methodologies with iterative development, continuous feedback, and regular deliverables.",
              },
              {
                id: "cmirrv6lg001314iwvoqg9aaq",
                question: "Do you offer consulting services?",
                answer:
                  "Yes, we provide architecture reviews, technology assessments, and strategic consulting services.",
              },
              {
                id: "cmirrv6lg001414iw8knu02fq",
                question: "How do you ensure code quality?",
                answer:
                  "We implement automated testing, code reviews, CI/CD pipelines, and follow industry best practices.",
              },
            ],
            contentFaqsCount: 8,
            contentTestimonials: null,
            contentCertifications: null,
            contentApproach: null,
            contentAbout: null,
            contentAnalytics: null,
            contentNavigation: null,
            contentFooter: null,
            contentCta: null,
            contentMap: null,
          },
          {
            id: "cmirrv6m2003b14iw58xgdu5b",
            type: "navigation",
            contentHero: null,
            contentBenefits: null,
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: null,
            contentCertifications: null,
            contentApproach: null,
            contentAbout: null,
            contentAnalytics: null,
            contentNavigation: {
              id: "cmirrv6ll001t14iw6i91c9wy",
              title: "Navigation",
              description:
                "Quick links to explore our services and get in touch.",
              image: {
                id: "cmirrv6jr000514iw9lq89so6",
                src: "/images/nav-bg.png",
                alt: "Navigation background",
                width: 1600,
                height: 900,
                fill: false,
                className: "",
              },
              cta: {
                id: "cmirrv6lk001o14iwubn2j4k5",
                label: "Contact Us",
                href: "mailto:r.khanduri@nimbus-tech.de,f.zeidler@nimbus-tech.de",
                external: false,
              },
              items: [
                {
                  id: "cmirrv6ll001p14iw6xqwurik",
                  label: "Services",
                  href: "#features",
                  external: false,
                  icon: "",
                },
                {
                  id: "cmirrv6ll001q14iwf0d1mcwj",
                  label: "About Us",
                  href: "#about-us",
                  external: false,
                  icon: "",
                },
                {
                  id: "cmirrv6ll001r14iwmno0pit8",
                  label: "Blog",
                  href: "https://rohitkhanduri.substack.com",
                  external: true,
                  icon: "",
                },
                {
                  id: "cmirrv6ll001s14iw6wrulpfz",
                  label: "Contact",
                  href: "mailto:r.khanduri@nimbus-tech.de,f.zeidler@nimbus-tech.de",
                  external: false,
                  icon: "",
                },
              ],
              itemsCount: 4,
            },
            contentFooter: null,
            contentCta: null,
            contentMap: null,
          },
          {
            id: "cmirrv6m2003c14iwrhzb44ek",
            type: "map",
            contentHero: null,
            contentBenefits: null,
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: null,
            contentCertifications: null,
            contentApproach: null,
            contentAbout: null,
            contentAnalytics: null,
            contentNavigation: null,
            contentFooter: null,
            contentCta: null,
            contentMap: {
              id: "cmirrv6m0002t14iwnw81wlhp",
              title: "Where We Work",
              subheading: "Global Reach, Local Expertise",
              description:
                "Based in Germany, we serve clients worldwide with remote-first collaboration and on-site consulting when needed.",
            },
          },
          {
            id: "cmirrv6m2003d14iwfhgq75ts",
            type: "analytics",
            contentHero: null,
            contentBenefits: null,
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: null,
            contentCertifications: null,
            contentApproach: null,
            contentAbout: null,
            contentAnalytics: {
              id: "cmirrv6lz002m14iwehutqgkn",
              heading: "Project Analytics",
              subheading:
                "Real-time insights into our project performance and client satisfaction metrics.",
              stats: {
                id: "cmirrv6ly002h14iwbt42cvkt",
                totalDeployments: "150+",
                deploymentChange: "+12",
                deploymentChangePercent: "8.5%",
                changePeriod: "vs last month",
              },
              tableHeadings: [
                "project",
                "deployments",
                "uptime",
                "clientSatisfaction",
                "efficiency",
                "revenueGrowth",
              ],
              summary: [
                {
                  id: "cmirrv6ly002i14iw63lh2lad",
                  name: "E-Commerce Platform",
                  deployments: "45",
                  uptime: "99.9%",
                  clientSatisfaction: "4.8/5",
                  efficiency: "92%",
                  revenueGrowth: "+15%",
                  bgColor: "#F0F9FF",
                  changeType: "positive",
                },
                {
                  id: "cmirrv6ly002j14iw34ktx5vy",
                  name: "Healthcare Portal",
                  deployments: "38",
                  uptime: "99.7%",
                  clientSatisfaction: "4.9/5",
                  efficiency: "89%",
                  revenueGrowth: "+22%",
                  bgColor: "#F0FDF4",
                  changeType: "positive",
                },
                {
                  id: "cmirrv6ly002k14iwea59eywu",
                  name: "FinTech API",
                  deployments: "67",
                  uptime: "99.95%",
                  clientSatisfaction: "4.7/5",
                  efficiency: "94%",
                  revenueGrowth: "+18%",
                  bgColor: "#FEF3C7",
                  changeType: "positive",
                },
              ],
              summaryCount: 3,
            },
            contentNavigation: null,
            contentFooter: null,
            contentCta: null,
            contentMap: null,
          },
          {
            id: "cmirrv6m2003e14iwsnk5iata",
            type: "about",
            contentHero: null,
            contentBenefits: null,
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: null,
            contentCertifications: null,
            contentApproach: null,
            contentAbout: {
              id: "cmirrv6m0002s14iw44yegqtr",
              heading: "About Nimbus Tech",
              intro:
                "We are a team of passionate software engineers and cloud architects dedicated to helping businesses leverage modern technology for growth and innovation.",
              valuesTitle: "Our Values",
              values: [
                {
                  id: "cmirrv6lz002n14iwu9gr5upl",
                  label: "Excellence",
                  description:
                    "We strive for excellence in everything we do, from code quality to client communication.",
                  icon: "RiStarFill",
                },
                {
                  id: "cmirrv6lz002o14iwfel0hoyz",
                  label: "Innovation",
                  description:
                    "We embrace new technologies and methodologies to deliver cutting-edge solutions.",
                  icon: "RiLightbulbFill",
                },
                {
                  id: "cmirrv6lz002p14iwrajpe6sj",
                  label: "Transparency",
                  description:
                    "We believe in open communication and honest relationships with our clients.",
                  icon: "RiEyeFill",
                },
                {
                  id: "cmirrv6lz002q14iw7po6ae9v",
                  label: "Collaboration",
                  description:
                    "We work closely with our clients as partners to achieve shared goals.",
                  icon: "RiTeamFill",
                },
                {
                  id: "cmirrv6lz002r14iwkv65wsia",
                  label: "Reliability",
                  description:
                    "We deliver on our promises and build systems that our clients can depend on.",
                  icon: "RiShieldCheckFill",
                },
              ],
              valuesCount: 5,
              closing:
                "Ready to transform your business with cloud technology? Let's build something amazing together.",
            },
            contentAnalytics: null,
            contentNavigation: null,
            contentFooter: null,
            contentCta: null,
            contentMap: null,
          },
          {
            id: "cmirrv6m2003f14iw0ephbhma",
            type: "cta",
            contentHero: null,
            contentBenefits: null,
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: null,
            contentCertifications: null,
            contentApproach: null,
            contentAbout: null,
            contentAnalytics: null,
            contentNavigation: null,
            contentFooter: null,
            contentCta: {
              id: "cmirrv6m1002w14iw87lcqagc",
              title: "Ready to Start Your Project?",
              description:
                "Let's discuss how we can help you achieve your technology goals. Get in touch for a free consultation.",
              ctas: [
                {
                  id: "cmirrv6m1002u14iwkyf52tzk",
                  label: "Schedule a Call",
                  href: "mailto:r.khanduri@nimbus-tech.de",
                  external: false,
                },
                {
                  id: "cmirrv6m1002v14iwqln3tuch",
                  label: "View Our Work",
                  href: "#case-studies",
                  external: false,
                },
              ],
              ctasCount: 2,
              background: [
                {
                  id: "cmirrv6l3000h14iwfb97lphm",
                  image: {
                    id: "cmirrv6jr000314iwggwjurgq",
                    src: "/images/cta-bg-1.png",
                    alt: "CTA background",
                    width: 800,
                    height: 600,
                    fill: false,
                    className: "object-cover",
                  },
                  outerClassName: "cta-background-1",
                },
                {
                  id: "cmirrv6l3000k14iw4kbz5scf",
                  image: {
                    id: "cmirrv6jr000114iwihlpb4g6",
                    src: "/images/cta-bg-2.png",
                    alt: "CTA background 2",
                    width: 800,
                    height: 600,
                    fill: false,
                    className: "object-cover",
                  },
                  outerClassName: "cta-background-2",
                },
              ],
              backgroundCount: 2,
            },
            contentMap: null,
          },
          {
            id: "cmirrv6m3003h14iwl0cgfwo2",
            type: "footer",
            contentHero: null,
            contentBenefits: null,
            contentFeatures: [],
            contentFeaturesCount: 0,
            contentFaqs: [],
            contentFaqsCount: 0,
            contentTestimonials: null,
            contentCertifications: null,
            contentApproach: null,
            contentAbout: null,
            contentAnalytics: null,
            contentNavigation: null,
            contentFooter: {
              id: "cmirrv6lx002g14iwuct52gnf",
              title: "Nimbus Tech",
              sections: [
                {
                  id: "cmirrv6lm002a14iwh523faio",
                  title: "Services",
                  items: [
                    {
                      id: "cmirrv6lm001u14iwa4j9m8bd",
                      label: "Cloud Architecture",
                      href: "#features",
                      external: false,
                      icon: "",
                    },
                    {
                      id: "cmirrv6lm001w14iwxxesfx18",
                      label: "Software Development",
                      href: "#features",
                      external: false,
                      icon: "",
                    },
                    {
                      id: "cmirrv6lm001x14iwvmj1ipxr",
                      label: "DevOps Consulting",
                      href: "#features",
                      external: false,
                      icon: "",
                    },
                    {
                      id: "cmirrv6lm002014iwdmanpm8i",
                      label: "Technical Training",
                      href: "#features",
                      external: false,
                      icon: "",
                    },
                    {
                      id: "cmirrv6lm002214iwh2xosqar",
                      label: "Architecture Review",
                      href: "#features",
                      external: false,
                      icon: "",
                    },
                  ],
                  itemsCount: 5,
                },
                {
                  id: "cmirrv6ln002b14iwsyeeytfy",
                  title: "Company",
                  items: [
                    {
                      id: "cmirrv6lm001v14iwl37640hg",
                      label: "About Us",
                      href: "#about-us",
                      external: false,
                      icon: "",
                    },
                    {
                      id: "cmirrv6lm001y14iwrmr5k1wz",
                      label: "Blog",
                      href: "https://rohitkhanduri.substack.com",
                      external: true,
                      icon: "",
                    },
                    {
                      id: "cmirrv6lm002114iw7o820909",
                      label: "Careers",
                      href: "#careers",
                      external: false,
                      icon: "",
                    },
                    {
                      id: "cmirrv6lm002414iwhs6z1gsl",
                      label: "LinkedIn",
                      href: "https://linkedin.com/company/nimbus-tech",
                      external: true,
                      icon: "",
                    },
                  ],
                  itemsCount: 4,
                },
                {
                  id: "cmirrv6lq002c14iw89q3umh5",
                  title: "Social",
                  items: [
                    {
                      id: "cmirrv6lm002614iwd9hqbk33",
                      label: "GitHub",
                      href: "https://github.com/nimbus-tech",
                      external: true,
                      icon: "RiGithubFill",
                    },
                    {
                      id: "cmirrv6lm002814iwx65c7u8f",
                      label: "LinkedIn",
                      href: "https://linkedin.com/company/nimbus-tech",
                      external: true,
                      icon: "RiLinkedinFill",
                    },
                    {
                      id: "cmirrv6lm002914iwuvmpe8yi",
                      label: "Twitter",
                      href: "https://twitter.com/nimbustech",
                      external: true,
                      icon: "RiTwitterFill",
                    },
                  ],
                  itemsCount: 3,
                },
                {
                  id: "cmirrv6lw002d14iw00vq3hzr",
                  title: "Resources",
                  items: [
                    {
                      id: "cmirrv6lm001z14iwdlzgzrmx",
                      label: "Documentation",
                      href: "#docs",
                      external: false,
                      icon: "",
                    },
                    {
                      id: "cmirrv6lm002314iwjangaupf",
                      label: "Case Studies",
                      href: "#case-studies",
                      external: false,
                      icon: "",
                    },
                    {
                      id: "cmirrv6lm002514iw11cdzhy7",
                      label: "FAQ",
                      href: "#faq",
                      external: false,
                      icon: "",
                    },
                    {
                      id: "cmirrv6lm002714iw7u0arm31",
                      label: "Support",
                      href: "#support",
                      external: false,
                      icon: "",
                    },
                  ],
                  itemsCount: 4,
                },
              ],
              sectionsCount: 4,
              languages: [
                {
                  id: "cmirrv6lx002e14iw4iccwoqw",
                  label: "English",
                  value: "en-US",
                },
                {
                  id: "cmirrv6lx002f14iwb6y08i34",
                  label: "German",
                  value: "de-DE",
                },
              ],
              languagesCount: 2,
            },
            contentCta: null,
            contentMap: null,
          },
        ],
        sectionsCount: 13,
      },
    ],
  },
}
