import ts from "typescript"
import * as fs from "fs"
import * as path from "path"

async function generateRemixiconMap() {
  try {
    // Check dependencies
    const dtsPath = path.join(
      "node_modules",
      "@remixicon",
      "react",
      "index.d.ts",
    )
    if (!fs.existsSync(dtsPath)) {
      throw new Error(
        `@remixicon/react not found. Run: npm install @remixicon/react`,
      )
    }

    console.log("📖 Parsing @remixicon/react index.d.ts...")
    const content = fs.readFileSync(dtsPath, "utf8")
    const sourceFile = ts.createSourceFile(
      dtsPath,
      content,
      ts.ScriptTarget.Latest,
      true,
    )

    const iconNames: string[] = []

    function visit(node: ts.Node) {
      if (ts.isVariableStatement(node)) {
        for (const decl of node.declarationList.declarations) {
          if (
            ts.isIdentifier(decl.name) &&
            decl.type &&
            ts.isTypeReferenceNode(decl.type) &&
            decl.type.typeName.getText(sourceFile) === "RemixiconComponentType"
          ) {
            iconNames.push(decl.name.getText(sourceFile))
          }
        }
      }
      ts.forEachChild(node, visit)
    }

    visit(sourceFile)

    if (iconNames.length === 0) {
      throw new Error(
        "No RemixiconComponentType declarations found in index.d.ts",
      )
    }

    // Generate map code
    const mapCode = `// Generated by scripts/generateIcons.ts
      // DO NOT EDIT THIS FILE MANUALLY
      // If you need to update the icons, run \`npm run icons:generate\`
      // Read the README.md for more information
      import * as RiIcons from "@remixicon/react";

export const remixIconMap: Record<string, RiIcons.RemixiconComponentType> = {
${iconNames.map((name) => `  "${name}": RiIcons.${name},`).join("\n")}
};`

    // Write output
    const outputPath = path.join(
      process.cwd(),
      "src",
      "icons",
      "remixicon-map.ts",
    )
    const outputDir = path.dirname(outputPath)

    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true })
    }

    fs.writeFileSync(outputPath, mapCode)

    console.log(
      `✅ Generated remixicon-map.ts with ${iconNames.length} icons at ${outputPath}`,
    )
    console.log(`📦 Total size: ${mapCode.length} characters`)
  } catch (error) {
    console.error("❌ Generation failed:", (error as Error).message)
    process.exit(1)
  }
}

generateRemixiconMap()
